# Assignment-2 : Keras Machine Learning Model #

### Submitted by Dhananjay Kumar : 135297208

In [2]:
# Importing the libraries

from numpy import array
from keras.preprocessing.text import one_hot
from keras_preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

In [3]:
# Creating a sample dataset of text

mytext = ['can I order pizza', 'can we go to the mall', 'can I drive', 'yes lets order pizza', 'yes in the evening', 'yes you can drive']

In [4]:
# Defining the class labels for Dataset

mytextlabels = array([1, 1, 1, 0, 0, 0])


In [6]:
# Encoding the test dataset using one_hot encoding

textvocabs = 30
encodtext = [one_hot(i,textvocabs) for i in mytext]
print(encodtext)

[[10, 9, 22, 4], [10, 7, 28, 29, 8, 23], [10, 9, 11], [10, 14, 22, 4], [10, 26, 8, 8], [10, 29, 10, 11]]


### <U> Explanation: </U>
Deep learning methods cannot work with categorical data directly. Categorical data must be converted into numbers in order to work on them. That's why we used one hot encoding to convert the categorical values to integer values. One hot encoding converts the categorical value into binary vectors.

In [7]:
# Padding the encoded dataset to a max length of 7

length = 7
padmytext = pad_sequences(encodtext, maxlen=length,padding='pre')
print(padmytext)


[[ 0  0  0 10  9 22  4]
 [ 0 10  7 28 29  8 23]
 [ 0  0  0  0 10  9 11]
 [ 0  0  0 10 14 22  4]
 [ 0  0  0 10 26  8  8]
 [ 0  0  0 10 29 10 11]]


In [8]:
# Creating a machine learning model

mymodel = Sequential()
mymodel.add(Embedding(textvocabs, 8, input_length=length))
mymodel.add(Flatten())
mymodel.add(Dense(1, activation = 'sigmoid'))
mymodel.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
mymodel.fit(padmytext,mytextlabels, epochs=30)


Epoch 1/30
1/1 [==============================] - 2s 2s/step - loss: 0.6853 - accuracy: 0.8333
Epoch 2/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6838 - accuracy: 0.8333
Epoch 3/30
1/1 [==============================] - 0s 10ms/step - loss: 0.6823 - accuracy: 0.8333
Epoch 4/30
1/1 [==============================] - 0s 8ms/step - loss: 0.6809 - accuracy: 0.8333
Epoch 5/30
1/1 [==============================] - 0s 7ms/step - loss: 0.6794 - accuracy: 0.8333
Epoch 6/30
1/1 [==============================] - 0s 7ms/step - loss: 0.6780 - accuracy: 0.8333
Epoch 7/30
1/1 [==============================] - 0s 11ms/step - loss: 0.6765 - accuracy: 0.8333
Epoch 8/30
1/1 [==============================] - 0s 9ms/step - loss: 0.6751 - accuracy: 0.8333
Epoch 9/30
1/1 [==============================] - 0s 9ms/step - loss: 0.6736 - accuracy: 0.8333
Epoch 10/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6722 - accuracy: 0.8333
Epoch 11/30
1/1 [=====================

### <U> Findings from the model </U>
We can see that the loss is 64% and accuracy is 100%. Ideal model should have the lowest loss and highest accuracy (Closer to 1.0 or 100%). Based on above results, we can say our model is performing well.

In [9]:
# Creating a prediction model

predict_text =['Yes I can speak German', 'Can you speak German']

# Encoding the prediction text using one_hot

vocab_text = 30
encod_ptext= [one_hot(d, vocab_text) for d in predict_text]
print(encod_ptext)


[[10, 9, 10, 1, 27], [10, 29, 1, 27]]


In [10]:
# Padding the the encoded_text

max_length = 7
pred_paded = pad_sequences(encod_ptext, maxlen= max_length, padding='pre')
print(pred_paded)


[[ 0  0 10  9 10  1 27]
 [ 0  0  0 10 29  1 27]]


In [11]:
# Results of prediction model

ypred = mymodel.predict(pred_paded)
print(ypred)

1/1 [==============================] - 0s 193ms/step
[[0.50589156]
 [0.47289318]]


In [12]:
# Rounding off the prediction score

import numpy as np
print(np.around(ypred))

[[1.]
 [0.]]


In [36]:
# Testing the prediction model

topredict =['yes i love going to parties', 'Can we go outside', 'Where can we go', 'yes i will go for a picnic']

test_vocab = 30
encod_test= [one_hot(d, test_vocab) for d in topredict]
print(encod_test)

[[10, 9, 27, 7, 29, 3], [10, 7, 28, 27], [5, 10, 7, 28], [10, 9, 17, 28, 19, 11, 7]]


In [37]:
# Padding the test model

max_length = 7
test_paded = pad_sequences(encod_test, maxlen= max_length, padding='pre')
print(test_paded)


[[ 0 10  9 27  7 29  3]
 [ 0  0  0 10  7 28 27]
 [ 0  0  0  5 10  7 28]
 [10  9 17 28 19 11  7]]


In [38]:
# Result of test model

predictions = mymodel.predict(test_paded)

1/1 [==============================] - 0s 81ms/step


In [39]:
# Final result after rounding off

import numpy as np
print(np.around(predictions))

[[1.]
 [0.]
 [0.]
 [1.]]


## <U> Conclusion: </U> 
Based on the outcomes of our prediction model, we can see that our model categorised questions as 0 and answers as 1. However, it's worth noting that "Where" was categorised as a question, despite the fact that we only trained our model with can.